// angular-frontend/src/app/channel-manager/streams-pane/streams-pane.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, EventEmitter, inject, Input, OnInit, OnDestroy, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../api.service';
import { TuiLoader } from '@taiga-ui/core';
import { VideoPlayerComponent } from '../video-player/video-player.component';

// =================== INTERFACES ===================

interface M3UView {
  id: number;
  name: string;
  status: string;
  last_refreshed: string | null;
  expanded: boolean;
  groups: M3UGroupView[];
  total_streams: number;
}

interface M3UGroupView {
  name: string;
  expanded: boolean;
  streams: any[];
}

@Component({
  selector: 'app-streams-pane',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    TuiLoader,
    VideoPlayerComponent
  ],
  templateUrl: './streams-pane.html',
  styleUrl: './streams-pane.less',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StreamsPaneComponent implements OnInit, OnDestroy {
  private readonly api = inject(ApiService);
  private readonly cdr = inject(ChangeDetectorRef);

  // =================== DATA ===================
  
  m3uViews: M3UView[] = [];
  allM3Us: any[] = [];
  allGroups: string[] = [];
  
  /** Lookup: channel_group_id → group name (resolved from /api/channels/groups/) */
  private channelGroupNames: Map<number, string> = new Map();

  /** Set of stream IDs that are already assigned to at least one channel */
  assignedStreamIds: Set<number> = new Set();

  loading = false;
  refreshingIds: Set<number> = new Set();

  // =================== SELECTION (self-managed) ===================

  /** Internally managed set of selected stream IDs */
  selectedStreamIds: Set<number> = new Set();

  /** Flat ordered list of all visible stream IDs for shift-click range selection */
  private flatStreamIds: number[] = [];
  /** Index of the last clicked stream for shift-click computation */
  private lastClickedStreamIdx = -1;

  // =================== FILTERS ===================

  searchQuery = '';
  selectedProviderFilters: Set<number> = new Set();
  selectedGroupFilters: Set<string> = new Set();

  /** When true, streams already assigned to a channel are hidden */
  hideAssigned = false;

  showProviderDropdown = false;
  showGroupDropdown = false;

  providerSearch = '';
  groupSearch = '';

  // =================== VIDEO PLAYER ===================

  playerUrl: string | null = null;
  playerTitle = '';

  ngOnInit() {
    this.loadData();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private loadData() {
    this.loading = true;
    this.cdr.markForCheck();

    // Step 1: Fetch channel groups so we can resolve IDs → names
    this.api.getChannelGroups().subscribe((groupsRes: any) => {
      const groups = Array.isArray(groupsRes) ? groupsRes : groupsRes?.results || [];
      this.channelGroupNames.clear();
      groups.forEach((g: any) => this.channelGroupNames.set(g.id, g.name));

      // Step 2: Fetch channels to build the set of assigned stream IDs
      this.api.getChannels({ page_size: 5000 }).subscribe((channelsRes: any) => {
        const channels = Array.isArray(channelsRes) ? channelsRes : channelsRes?.results || [];
        this.assignedStreamIds.clear();
        channels.forEach((ch: any) => {
          const streams = ch.streams || [];
          streams.forEach((s: any) => this.assignedStreamIds.add(s.id));
        });

        // Step 3: Fetch playlists (providers)
        this.api.getPlaylists().subscribe((m3us: any) => {
          this.allM3Us = Array.isArray(m3us) ? m3us : m3us?.results || [];
          
          // Step 4: Fetch all streams to build the tree
          this.api.getStreams({ page_size: 10000 }).subscribe({
            next: (streamsRes: any) => {
              const streams = Array.isArray(streamsRes) ? streamsRes : streamsRes?.results || [];
              this.buildTree(this.allM3Us, streams);
              this.loading = false;
              this.cdr.markForCheck();
            },
            error: (err) => {
              console.error('Failed to fetch streams:', err);
              this.loading = false;
              this.cdr.markForCheck();
            }
          });
        });
      });
    });
  }

  private buildTree(m3us: any[], streams: any[]) {
    // Collect all unique group names for the filter dropdown
    const groupsSet = new Set<string>();
    streams.forEach(s => {
      const groupName = this.resolveGroupName(s.channel_group);
      if (groupName) groupsSet.add(groupName);
    });
    this.allGroups = Array.from(groupsSet).sort();

    // Group streams by M3U Account ID, then by resolved Group Name
    const streamsByM3U = new Map<number, Map<string, any[]>>();

    streams.forEach(s => {
      const m3uId = s.m3u_account_id ?? s.m3u_account;
      if (m3uId === undefined || m3uId === null) return;

      if (!streamsByM3U.has(m3uId)) {
        streamsByM3U.set(m3uId, new Map<string, any[]>());
      }
      
      const groupName = this.resolveGroupName(s.channel_group) || 'Ungrouped';
      const m3uGroups = streamsByM3U.get(m3uId)!;
      
      if (!m3uGroups.has(groupName)) {
        m3uGroups.set(groupName, []);
      }
      m3uGroups.get(groupName)!.push(s);
    });

    // Preserve existing expansion state when rebuilding the tree
    const previousExpandedM3U = new Set(this.m3uViews.filter(m => m.expanded).map(m => m.id));
    const previousExpandedGroups = new Set<string>();
    this.m3uViews.forEach(m => {
      m.groups.forEach(g => {
        if (g.expanded) previousExpandedGroups.add(`${m.id}::${g.name}`);
      });
    });

    // Build M3U views — show ALL providers, even those with 0 streams
    this.m3uViews = m3us.map(m => {
      const m3uGroups = streamsByM3U.get(m.id) || new Map<string, any[]>();
      const groups: M3UGroupView[] = Array.from(m3uGroups.keys()).sort().map(name => ({
        name,
        expanded: previousExpandedGroups.has(`${m.id}::${name}`),
        streams: m3uGroups.get(name)!
      }));

      const totalStreams = groups.reduce((acc, g) => acc + g.streams.length, 0);

      return {
        id: m.id,
        name: m.name,
        status: m.status || 'idle',
        last_refreshed: m.updated_at || m.last_refreshed,
        expanded: previousExpandedM3U.has(m.id),
        groups,
        total_streams: totalStreams
      };
    });

    // Rebuild flat stream ID list for shift-click
    this.rebuildFlatStreamIds();
  }

  /**
   * Resolve a channel_group value to a human-readable group name.
   */
  private resolveGroupName(channelGroup: any): string {
    if (channelGroup === null || channelGroup === undefined) return '';
    if (typeof channelGroup === 'number') {
      return this.channelGroupNames.get(channelGroup) || `Group #${channelGroup}`;
    }
    return String(channelGroup);
  }

  /**
   * Rebuild the flat ordered list of stream IDs from the current filtered view.
   * Used for shift-click range selection.
   */
  private rebuildFlatStreamIds() {
    this.flatStreamIds = [];
    this.filteredM3UViews.forEach(m => {
      m.groups.forEach(g => {
        g.streams.forEach(s => this.flatStreamIds.push(s.id));
      });
    });
  }

  // =================== FILTERS ===================

  get filteredM3UViews(): M3UView[] {
    return this.m3uViews.filter(m => {
      // Filter by provider
      if (this.selectedProviderFilters.size > 0 && !this.selectedProviderFilters.has(m.id)) {
        return false;
      }

      const hasGroupFilters = this.selectedGroupFilters.size > 0;
      const hasSearch = !!this.searchQuery;

      if (!hasGroupFilters && !hasSearch && !this.hideAssigned) return true;

      // Check if any group matches
      const matchingGroups = m.groups.filter(g => {
        if (hasGroupFilters && !this.selectedGroupFilters.has(g.name)) return false;
        
        // Filter out assigned streams if toggle is on
        let filteredStreams = g.streams;
        if (this.hideAssigned) {
          filteredStreams = filteredStreams.filter(s => !this.assignedStreamIds.has(s.id));
        }

        if (hasSearch) {
          filteredStreams = filteredStreams.filter(s => 
            s.name.toLowerCase().includes(this.searchQuery.toLowerCase())
          );
        }
        return filteredStreams.length > 0;
      });

      return matchingGroups.length > 0;
    }).map(m => {
      const hasGroupFilters = this.selectedGroupFilters.size > 0;
      const hasSearch = !!this.searchQuery;

      if (!hasGroupFilters && !hasSearch && !this.hideAssigned) return m;

      const filteredGroups = m.groups.filter(g => {
        if (hasGroupFilters && !this.selectedGroupFilters.has(g.name)) return false;
        
        let filteredStreams = g.streams;
        if (this.hideAssigned) {
          filteredStreams = filteredStreams.filter(s => !this.assignedStreamIds.has(s.id));
        }
        if (hasSearch) {
          filteredStreams = filteredStreams.filter(s => 
            s.name.toLowerCase().includes(this.searchQuery.toLowerCase())
          );
        }
        return filteredStreams.length > 0;
      }).map(g => {
        let filteredStreams = g.streams;
        if (this.hideAssigned) {
          filteredStreams = filteredStreams.filter(s => !this.assignedStreamIds.has(s.id));
        }
        if (hasSearch) {
          filteredStreams = filteredStreams.filter(s => 
            s.name.toLowerCase().includes(this.searchQuery.toLowerCase())
          );
        }
        return {
          ...g,
          expanded: hasSearch ? true : g.expanded,
          streams: filteredStreams
        };
      });

      return {
        ...m,
        expanded: hasSearch || m.expanded,
        groups: filteredGroups
      };
    });
  }

  /** Total stream count across all visible groups/providers */
  get totalVisibleStreamCount(): number {
    return this.filteredM3UViews.reduce((sum, m) =>
      sum + m.groups.reduce((gs, g) => gs + g.streams.length, 0), 0);
  }

  get providerFilterLabel(): string {
    if (this.selectedProviderFilters.size === 0) return 'All Providers';
    if (this.selectedProviderFilters.size === 1) {
      const id = Array.from(this.selectedProviderFilters)[0];
      return this.allM3Us.find(m => m.id === id)?.name || '1 Provider';
    }
    return `${this.selectedProviderFilters.size} Providers`;
  }

  get groupFilterLabel(): string {
    if (this.selectedGroupFilters.size === 0) return 'All Groups';
    if (this.selectedGroupFilters.size === 1) return Array.from(this.selectedGroupFilters)[0];
    return `${this.selectedGroupFilters.size} Groups`;
  }

  toggleProviderFilter(id: number) {
    if (this.selectedProviderFilters.has(id)) {
      this.selectedProviderFilters.delete(id);
    } else {
      this.selectedProviderFilters.add(id);
    }
    this.cdr.markForCheck();
  }

  toggleGroupFilter(name: string) {
    if (this.selectedGroupFilters.has(name)) {
      this.selectedGroupFilters.delete(name);
    } else {
      this.selectedGroupFilters.add(name);
    }
    this.cdr.markForCheck();
  }

  clearProviderFilters() {
    this.selectedProviderFilters.clear();
    this.cdr.markForCheck();
  }

  clearGroupFilters() {
    this.selectedGroupFilters.clear();
    this.cdr.markForCheck();
  }

  toggleHideAssigned() {
    this.hideAssigned = !this.hideAssigned;
    this.cdr.markForCheck();
  }

  get filteredProviders() {
    return this.allM3Us.filter(m => 
      m.name.toLowerCase().includes(this.providerSearch.toLowerCase())
    );
  }

  get filteredGroups() {
    return this.allGroups.filter(g => 
      g.toLowerCase().includes(this.groupSearch.toLowerCase())
    );
  }

  // =================== ACTIONS ===================

  refreshM3U(m3uId: number, event: Event) {
    event.stopPropagation();
    if (this.refreshingIds.has(m3uId)) return;

    this.refreshingIds.add(m3uId);
    this.cdr.markForCheck();

    this.api.refreshM3UAccount(m3uId).subscribe({
      next: () => {
        setTimeout(() => {
          this.refreshingIds.delete(m3uId);
          this.loadData();
        }, 2000);
      },
      error: (err) => {
        console.error('Refresh failed:', err);
        this.refreshingIds.delete(m3uId);
        this.cdr.markForCheck();
      }
    });
  }

  previewStream(stream: any, event: Event) {
    event.stopPropagation();
    this.playerUrl = `/stream/${stream.id}/`;
    this.playerTitle = stream.name;
    this.cdr.markForCheck();
  }

  // =================== SELECTION ===================

  isStreamSelected(id: number): boolean {
    return this.selectedStreamIds.has(id);
  }

  /**
   * Toggle a single stream's selection. Supports shift-click range selection.
   */
  onToggleStream(id: number, event: MouseEvent) {
    event.stopPropagation();

    // Rebuild flat IDs on every click to match current filter state
    this.rebuildFlatStreamIds();
    const idx = this.flatStreamIds.indexOf(id);

    if (event.shiftKey && this.lastClickedStreamIdx >= 0) {
      // Shift-click: select/deselect the range between last click and this one
      const start = Math.min(this.lastClickedStreamIdx, idx);
      const end = Math.max(this.lastClickedStreamIdx, idx);
      for (let i = start; i <= end; i++) {
        this.selectedStreamIds.add(this.flatStreamIds[i]);
      }
    } else {
      // Normal click: toggle single stream
      if (this.selectedStreamIds.has(id)) {
        this.selectedStreamIds.delete(id);
      } else {
        this.selectedStreamIds.add(id);
      }
    }

    this.lastClickedStreamIdx = idx;
    this.cdr.markForCheck();
  }

  /** Select all visible streams */
  selectAllStreams() {
    this.rebuildFlatStreamIds();
    this.flatStreamIds.forEach(id => this.selectedStreamIds.add(id));
    this.cdr.markForCheck();
  }

  /** Deselect all streams */
  deselectAllStreams() {
    this.selectedStreamIds.clear();
    this.lastClickedStreamIdx = -1;
    this.cdr.markForCheck();
  }

  /** Returns true if all visible streams are currently selected */
  get allVisibleSelected(): boolean {
    if (this.totalVisibleStreamCount === 0) return false;
    this.rebuildFlatStreamIds();
    return this.flatStreamIds.every(id => this.selectedStreamIds.has(id));
  }

  // =================== EXPAND / COLLAPSE ===================

  toggleM3UExpand(m3u: M3UView) {
    m3u.expanded = !m3u.expanded;
    this.cdr.markForCheck();
  }

  toggleGroupExpand(group: M3UGroupView, event: Event) {
    event.stopPropagation();
    group.expanded = !group.expanded;
    this.cdr.markForCheck();
  }

  expandAll() {
    this.filteredM3UViews.forEach(m => {
      m.expanded = true;
      m.groups.forEach(g => g.expanded = true);
    });
    this.cdr.markForCheck();
  }

  collapseAll() {
    this.filteredM3UViews.forEach(m => {
      m.expanded = false;
      m.groups.forEach(g => g.expanded = false);
    });
    this.cdr.markForCheck();
  }

  // =================== HELPERS ===================

  onDocumentClick() {
    this.showProviderDropdown = false;
    this.showGroupDropdown = false;
    this.cdr.markForCheck();
  }

  handleDragStart(event: DragEvent, stream: any) {
    if (event.dataTransfer) {
      // If the dragged stream is selected, drag ALL selected streams.
      // Otherwise, drag just the single stream.
      const idsToDrag = this.selectedStreamIds.has(stream.id) 
        ? Array.from(this.selectedStreamIds)
        : [stream.id];
        
      event.dataTransfer.setData('application/json', JSON.stringify(idsToDrag));
      event.dataTransfer.effectAllowed = 'copy';
      
      const dragEl = document.createElement('div');
      dragEl.textContent = `${idsToDrag.length} stream(s)`;
      dragEl.style.cssText = 'position: absolute; top: -1000px; background: #646cff; color: white; padding: 4px 12px; border-radius: 6px; font-size: 13px; font-weight: 500;';
      document.body.appendChild(dragEl);
      event.dataTransfer.setDragImage(dragEl, 0, 0);
      setTimeout(() => document.body.removeChild(dragEl), 0);
    }
  }

  trackByM3UId(_: number, m: M3UView) { return m.id; }
  trackByGroupName(_: number, g: M3UGroupView) { return g.name; }
  trackByStreamId(_: number, s: any) { return s.id; }
}

// svelte-frontend/src/lib/components/channel-manager/StreamsPane.svelte
<script lang="ts">
	import { api } from '$lib/api';
	import { ChevronDown, ChevronRight, Play, Database, Layers, Eye, EyeOff } from 'lucide-svelte';
	import { onMount } from 'svelte';

	// --- Types ---
	interface Stream { id: number; name: string; url: string | null; channel_group: any; m3u_account_id: number; }
	interface M3UGroupView { name: string; expanded: boolean; streams: Stream[]; }
	interface M3UView { id: number; name: string; expanded: boolean; groups: M3UGroupView[]; total_streams: number; }

	// --- Props ---
	let { onPlayStream }: { onPlayStream?: (info: { url: string; title: string }) => void } = $props();

	// --- State ---
	let m3uViews = $state<M3UView[]>([]);
	let loading = $state(true);
	let searchQuery = $state('');
	let assignedStreamIds = $state(new Set<number>());
	let showUnassignedOnly = $state(false);
	let channelGroupNames = new Map<number, string>();

	// Multi-select
	let selectedIds = $state(new Set<number>());

	// Expose reload for parent
	export function reload() { loadData(); }

	// --- Load ---
	async function loadData() {
		loading = true;
		try {
			const [groups, channelsRes, m3us, streamsRes] = await Promise.all([
				api.getChannelGroups(),
				api.getChannels({ page_size: 5000 }),
				api.getPlaylists(),
				api.getStreams({ page_size: 10000 })
			]);
			const groupList  = Array.isArray(groups)      ? groups      : groups.results      || [];
			const channelList= Array.isArray(channelsRes) ? channelsRes : channelsRes.results || [];
			const playlistList= Array.isArray(m3us)       ? m3us        : m3us.results        || [];
			const streamList = Array.isArray(streamsRes)  ? streamsRes  : streamsRes.results  || [];

			groupList.forEach((g: any) => channelGroupNames.set(g.id, g.name));

			const assigned = new Set<number>();
			channelList.forEach((ch: any) => (ch.streams || []).forEach((s: any) => assigned.add(s.id)));
			assignedStreamIds = assigned;

			buildTree(playlistList, streamList);
		} catch (e) {
			console.error('Failed to load streams:', e);
		} finally {
			loading = false;
		}
	}

	function resolveGroupName(channelGroup: any): string {
		if (channelGroup == null) return '';
		if (typeof channelGroup === 'number') return channelGroupNames.get(channelGroup) || `Group #${channelGroup}`;
		return String(channelGroup);
	}

	function buildTree(m3us: any[], streams: any[]) {
		const byM3U = new Map<number, Map<string, any[]>>();
		streams.forEach(s => {
			const m3uId = s.m3u_account_id ?? s.m3u_account;
			if (m3uId == null) return;
			if (!byM3U.has(m3uId)) byM3U.set(m3uId, new Map());
			const groupName = resolveGroupName(s.channel_group) || 'Ungrouped';
			const grp = byM3U.get(m3uId)!;
			if (!grp.has(groupName)) grp.set(groupName, []);
			grp.get(groupName)!.push(s);
		});
		m3uViews = m3us.map(m => {
			const grps = byM3U.get(m.id) || new Map();
			const groups = Array.from(grps.keys()).sort().map(name => ({ name, expanded: false, streams: grps.get(name)! }));
			return { id: m.id, name: m.name, expanded: false, groups, total_streams: groups.reduce((a, g) => a + g.streams.length, 0) };
		}).filter(m => m.total_streams > 0);
	}

	// --- Filtered view ---
	let filteredM3Us = $derived(
		m3uViews.map(m => {
			if (!searchQuery.trim() && !showUnassignedOnly) return m;
			const q = searchQuery.toLowerCase();
			const matchedGroups = m.groups.map(g => {
				let streams = g.streams;
				if (showUnassignedOnly) streams = streams.filter(s => !assignedStreamIds.has(s.id));
				if (q) streams = streams.filter(s => s.name.toLowerCase().includes(q));
				return streams.length > 0 ? { ...g, streams, expanded: true } : null;
			}).filter((g): g is M3UGroupView => g !== null);
			return matchedGroups.length > 0 ? { ...m, groups: matchedGroups, expanded: !!(searchQuery || showUnassignedOnly) } : null;
		}).filter((m): m is M3UView => m !== null)
	);

	// --- Selection ---
	function toggleSelect(streamId: number, e: MouseEvent) {
		// Shift-click: range select within visible list (simplified: just toggle)
		const next = new Set(selectedIds);
		if (next.has(streamId)) next.delete(streamId); else next.add(streamId);
		selectedIds = next;
	}

	function toggleGroupSelect(streams: Stream[]) {
		const ids = streams.map(s => s.id);
		const allSelected = ids.every(id => selectedIds.has(id));
		const next = new Set(selectedIds);
		if (allSelected) ids.forEach(id => next.delete(id)); else ids.forEach(id => next.add(id));
		selectedIds = next;
	}

	// --- Drag (single or multi-select) ---
	function handleDragStart(e: DragEvent, stream: Stream) {
		// If this stream is part of a selection, drag all selected; otherwise drag just this one
		const ids = selectedIds.has(stream.id) && selectedIds.size > 1
			? Array.from(selectedIds)
			: [stream.id];
		if (e.dataTransfer) {
			e.dataTransfer.setData('application/json', JSON.stringify(ids));
			e.dataTransfer.effectAllowed = 'copy';
		}
	}

	// --- Play ---
	function playStream(stream: Stream) {
		if (onPlayStream && stream.url) {
			onPlayStream({ url: stream.url, title: stream.name });
		}
	}

	onMount(() => { loadData(); });
</script>

<div class="streams-pane">
	<!-- Header -->
	<div class="pane-header">
		<input type="text" bind:value={searchQuery} placeholder="Search streams…" class="search-input" />
		<button
			class="filter-btn"
			class:active={showUnassignedOnly}
			title={showUnassignedOnly ? 'Showing unassigned only' : 'Show all streams'}
			onclick={() => showUnassignedOnly = !showUnassignedOnly}
		>
			{#if showUnassignedOnly}<Eye size={15} />{:else}<EyeOff size={15} />{/if}
			{showUnassignedOnly ? 'Unassigned' : 'All'}
		</button>
	</div>

	<!-- Selection bar -->
	{#if selectedIds.size > 0}
		<div class="selection-bar">
			<span>{selectedIds.size} stream{selectedIds.size > 1 ? 's' : ''} selected</span>
			<button onclick={() => selectedIds = new Set()}>Clear</button>
		</div>
	{/if}

	<div class="pane-content">
		{#if loading}
			<div class="state-msg">Loading streams…</div>
		{:else if filteredM3Us.length === 0}
			<div class="state-msg">No streams found.</div>
		{:else}
			{#each filteredM3Us as m3u (m3u.id)}
				<!-- M3U ACCOUNT ROW -->
				<div class="m3u-row">
					<button class="expand-btn" onclick={() => m3u.expanded = !m3u.expanded}>
						{#if m3u.expanded}<ChevronDown size={15}/>{:else}<ChevronRight size={15}/>{/if}
						<Database size={14} class="icon-dim" />
						<span class="m3u-name">{m3u.name}</span>
						<span class="badge">{m3u.total_streams}</span>
					</button>
				</div>

				{#if m3u.expanded}
					<div class="groups-list">
						{#each m3u.groups as group (group.name)}
							<!-- GROUP ROW -->
							<div class="group-row">
								<button class="expand-btn-group" onclick={() => group.expanded = !group.expanded}>
									{#if group.expanded}<ChevronDown size={13}/>{:else}<ChevronRight size={13}/>{/if}
									<Layers size={13} class="icon-dim" />
									<span class="group-name">{group.name}</span>
									<span class="badge-small">{group.streams.length}</span>
								</button>
								<!-- Select all in group -->
								{#if group.expanded}
									<button class="select-all-btn" title="Select/deselect all in group" onclick={() => toggleGroupSelect(group.streams)}>
										{group.streams.every(s => selectedIds.has(s.id)) ? '✓' : '○'}
									</button>
								{/if}
							</div>

							{#if group.expanded}
								<div class="streams-list">
									{#each group.streams as stream (stream.id)}
										<div
											class="stream-row"
											class:assigned={assignedStreamIds.has(stream.id)}
											class:selected={selectedIds.has(stream.id)}
											draggable="true"
											role="option"
											tabindex="0"
											aria-selected={selectedIds.has(stream.id)}
											ondragstart={(e) => handleDragStart(e, stream)}
											onclick={(e) => toggleSelect(stream.id, e)}
											onkeydown={(e) => e.key === ' ' && toggleSelect(stream.id, e as any)}
										>
											<!-- Checkbox -->
											<div class="stream-check" class:checked={selectedIds.has(stream.id)}>
												{#if selectedIds.has(stream.id)}✓{/if}
											</div>

											<div class="stream-info">
												<span class="stream-name">{stream.name}</span>
												{#if assignedStreamIds.has(stream.id)}
													<span class="assigned-badge">Assigned</span>
												{/if}
											</div>

											<div class="stream-actions">
												<!-- Play button -->
												{#if stream.url}
													<button class="icon-btn" title="Preview stream" onclick={(e) => { e.stopPropagation(); playStream(stream); }}>
														<Play size={12} fill="currentColor" />
													</button>
												{/if}
											</div>
										</div>
									{/each}
								</div>
							{/if}
						{/each}
					</div>
				{/if}
			{/each}
		{/if}
	</div>
</div>

<style lang="less">
.streams-pane { display: flex; flex-direction: column; height: 100%; background: var(--surface); border-radius: var(--radius); overflow: hidden; }

.pane-header {
	padding: 12px 16px; border-bottom: 1px solid var(--border);
	display: flex; gap: 8px; align-items: center;
	.search-input { flex: 1; background: var(--bg); border: 1px solid var(--border); padding: 8px 12px; border-radius: var(--radius); color: var(--text-bright); font-size: 13px; &:focus { outline: 1px solid var(--accent); } }
}

.filter-btn {
	display: flex; align-items: center; gap: 5px; padding: 7px 10px;
	background: var(--surface-bright); border: 1px solid var(--border); border-radius: var(--radius);
	color: var(--text-dim); font-size: 12px; cursor: pointer; white-space: nowrap;
	transition: all 0.15s;
	&.active { border-color: var(--accent); color: var(--accent); background: rgba(237,28,36,0.1); }
	&:hover:not(.active) { border-color: var(--border-bright); color: var(--text-bright); }
}

.selection-bar {
	display: flex; align-items: center; justify-content: space-between;
	padding: 6px 16px; background: rgba(237,28,36,0.1); border-bottom: 1px solid rgba(237,28,36,0.25);
	font-size: 12px; color: var(--accent);
	button { background: transparent; border: none; color: var(--text-dim); cursor: pointer; font-size: 11px; &:hover { color: var(--text-bright); } }
}

.pane-content { flex: 1; overflow-y: auto; padding: 8px 0; }
.state-msg { padding: 32px; text-align: center; color: var(--text-dim); font-style: italic; font-size: 13px; }

.expand-btn, .expand-btn-group {
	width: 100%; display: flex; align-items: center; gap: 7px; background: transparent; border: none;
	color: var(--text-bright); cursor: pointer; text-align: left; transition: background 0.15s;
	&:hover { background: rgba(255,255,255,0.05); }
}
.expand-btn { padding: 8px 16px; font-size: 13px; font-weight: 700; }
.expand-btn-group { padding: 5px 16px 5px 28px; font-size: 12px; font-weight: 600; color: var(--text-dim); flex: 1; }
.group-row { display: flex; align-items: center; }
.select-all-btn { background: transparent; border: none; color: var(--text-dim); font-size: 13px; padding: 4px 12px; cursor: pointer; &:hover { color: var(--accent); } }
.m3u-name, .group-name { flex: 1; }
.badge, .badge-small { font-size: 10px; background: var(--surface-bright); padding: 1px 6px; border-radius: 10px; color: var(--text-dim); }
:global(.icon-dim) { color: var(--text-dim); }

.stream-row {
	display: flex; align-items: center; gap: 6px;
	padding: 5px 16px 5px 48px; cursor: grab; transition: background 0.15s;
	&:hover { background: rgba(255,255,255,0.03); .stream-actions { opacity: 1; } }
	&.assigned .stream-name { color: var(--text-dim); }
	&.selected { background: rgba(237,28,36,0.08); }
}
.stream-check {
	width: 16px; height: 16px; border: 1px solid var(--border-bright); border-radius: 3px;
	display: flex; align-items: center; justify-content: center; font-size: 11px;
	color: var(--accent); flex-shrink: 0; transition: all 0.15s;
	&.checked { background: rgba(237,28,36,0.2); border-color: var(--accent); }
}
.stream-info { display: flex; align-items: center; gap: 7px; flex: 1; min-width: 0; .stream-name { font-size: 12px; color: var(--text-bright); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; } }
.assigned-badge { font-size: 9px; text-transform: uppercase; color: #4ade80; font-weight: 700; letter-spacing: 0.5px; flex-shrink: 0; }
.stream-actions { display: flex; gap: 3px; opacity: 0; transition: opacity 0.15s; flex-shrink: 0; }
.icon-btn { background: transparent; border: none; color: var(--text-dim); padding: 3px; border-radius: 4px; cursor: pointer; display: flex; align-items: center; &:hover { color: #4ade80; background: rgba(74,222,128,0.1); } }
</style>
