// angular-frontend/src/app/channel-manager/video-player/video-player.component.ts
import {
  Component, Input, Output, EventEmitter,
  ViewChild, ElementRef, OnChanges, OnDestroy,
  SimpleChanges, ChangeDetectionStrategy, ChangeDetectorRef
} from '@angular/core';
import { CommonModule } from '@angular/common';

// mpegts.js is imported dynamically to avoid SSR issues
declare var mpegts: any;

/**
 * In-app floating video player for previewing live streams and channels.
 * Uses mpegts.js for MPEG-TS live playback and native HTML5 <video> for VOD.
 *
 * Usage:
 *   <app-video-player
 *     [streamUrl]="'/stream/abc123/'"
 *     [title]="'Channel Name'"
 *     [contentType]="'live'"
 *     (closed)="onPlayerClosed()"
 *   ></app-video-player>
 */
@Component({
  selector: 'app-video-player',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- Overlay backdrop -->
    <div class="player-overlay" *ngIf="streamUrl" (click)="close()">
      <div class="player-container" (click)="$event.stopPropagation()">
        <!-- Header bar -->
        <div class="player-header">
          <span class="player-title">{{ title || 'Preview' }}</span>
          <button class="player-close" (click)="close()" title="Close player">
            <span class="material-icons">close</span>
          </button>
        </div>

        <!-- Video element -->
        <div class="player-video-wrapper">
          <video #videoElement
            autoplay
            playsinline
            [muted]="false"
            controls
            style="width: 100%; height: 100%; background: #000;">
          </video>

          <!-- Loading spinner overlay -->
          <div class="player-loading" *ngIf="loading">
            <div class="spinner"></div>
            <span>Connecting...</span>
          </div>

          <!-- Error overlay -->
          <div class="player-error" *ngIf="errorMsg">
            <span class="material-icons" style="font-size: 32px;">error_outline</span>
            <span>{{ errorMsg }}</span>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .player-overlay {
      position: fixed;
      top: 0; left: 0; right: 0; bottom: 0;
      background: rgba(0, 0, 0, 0.7);
      z-index: 10000;
      display: flex;
      align-items: center;
      justify-content: center;
      animation: fadeIn 0.15s ease;
    }
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    .player-container {
      width: 640px;
      max-width: 90vw;
      background: #1a1a2e;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
    }
    .player-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 8px 12px;
      background: #16213e;
    }
    .player-title {
      font-size: 13px;
      font-weight: 600;
      color: #e0e0e0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .player-close {
      background: none;
      border: none;
      color: #888;
      cursor: pointer;
      padding: 4px;
      border-radius: 4px;
      transition: color 0.15s, background 0.15s;
    }
    .player-close:hover {
      color: #fff;
      background: rgba(255, 255, 255, 0.1);
    }
    .player-video-wrapper {
      position: relative;
      width: 100%;
      aspect-ratio: 16 / 9;
      background: #000;
    }
    .player-loading {
      position: absolute;
      top: 0; left: 0; right: 0; bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 12px;
      color: rgba(255, 255, 255, 0.7);
      font-size: 13px;
      background: rgba(0, 0, 0, 0.5);
    }
    .spinner {
      width: 32px; height: 32px;
      border: 3px solid rgba(255, 255, 255, 0.2);
      border-top-color: #646cff;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
    }
    @keyframes spin {
      to { transform: rotate(360deg); }
    }
    .player-error {
      position: absolute;
      top: 0; left: 0; right: 0; bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 8px;
      color: #ff6b6b;
      font-size: 13px;
      background: rgba(0, 0, 0, 0.7);
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VideoPlayerComponent implements OnChanges, OnDestroy {
  @Input() streamUrl: string | null = null;
  @Input() title: string = 'Preview';
  @Input() contentType: 'live' | 'vod' = 'live';
  @Output() closed = new EventEmitter<void>();

  @ViewChild('videoElement') videoEl!: ElementRef<HTMLVideoElement>;

  loading = false;
  errorMsg: string | null = null;
  private player: any = null;
  private mpegtsModule: any = null;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges) {
    if (changes['streamUrl']) {
      // Tear down old player, start new one after view updates
      this.destroyPlayer();
      if (this.streamUrl) {
        this.loading = true;
        this.errorMsg = null;
        this.cdr.markForCheck();
        // Wait for the view to render the <video> element
        setTimeout(() => this.initPlayer(), 50);
      }
    }
  }

  ngOnDestroy() {
    this.destroyPlayer();
  }

  close() {
    this.destroyPlayer();
    this.streamUrl = null;
    this.closed.emit();
  }

  private async initPlayer() {
    if (!this.streamUrl || !this.videoEl?.nativeElement) {
      this.loading = false;
      this.cdr.markForCheck();
      return;
    }

    const video = this.videoEl.nativeElement;

    if (this.contentType === 'vod') {
      // Native HTML5 playback for VOD content
      this.initVod(video);
    } else {
      // mpegts.js for live MPEG-TS streams
      await this.initLive(video);
    }
  }

  private initVod(video: HTMLVideoElement) {
    video.src = this.streamUrl!;
    video.load();

    video.oncanplay = () => {
      this.loading = false;
      this.cdr.markForCheck();
      video.play().catch(() => {});
    };

    video.onerror = () => {
      this.loading = false;
      this.errorMsg = 'Failed to load video. The stream may be offline.';
      this.cdr.markForCheck();
    };

    // Store a pseudo-player for cleanup
    this.player = {
      destroy: () => {
        video.removeAttribute('src');
        video.load();
        video.oncanplay = null;
        video.onerror = null;
      }
    };
  }

  private async initLive(video: HTMLVideoElement) {
    try {
      // Dynamically import mpegts.js
      if (!this.mpegtsModule) {
        this.mpegtsModule = (await import('mpegts.js' as any)).default;
      }
      const mpegts = this.mpegtsModule;

      if (!mpegts.getFeatureList().mseLivePlayback) {
        this.loading = false;
        this.errorMsg = 'Your browser does not support live stream playback.';
        this.cdr.markForCheck();
        return;
      }

      // Build absolute URL if relative
      let url = this.streamUrl!;
      if (url.startsWith('/') && typeof window !== 'undefined') {
        url = `${window.location.origin}${url}`;
      }

      const player = mpegts.createPlayer(
        { type: 'mpegts', url, isLive: true, cors: true },
        {
          enableWorker: true,
          enableStashBuffer: false,
          liveBufferLatencyChasing: false,
          liveSync: false,
          autoCleanupSourceBuffer: true,
          autoCleanupMaxBackwardDuration: 120,
          autoCleanupMinBackwardDuration: 60,
          reuseRedirectedURL: true,
        }
      );

      player.attachMediaElement(video);

      player.on(mpegts.Events.MEDIA_INFO, () => {
        this.loading = false;
        this.cdr.markForCheck();
        player.play().catch(() => {});
      });

      player.on(mpegts.Events.ERROR, (errorType: string, errorDetail: string) => {
        console.error('mpegts.js error:', errorType, errorDetail);
        this.loading = false;
        this.errorMsg = `Stream error: ${errorType}`;
        this.cdr.markForCheck();
      });

      player.load();
      this.player = player;
    } catch (err: any) {
      console.error('Failed to initialize live player:', err);
      this.loading = false;
      this.errorMsg = `Player init failed: ${err.message || err}`;
      this.cdr.markForCheck();
    }
  }

  private destroyPlayer() {
    if (this.player) {
      try {
        if (typeof this.player.pause === 'function') {
          this.player.pause();
        }
        this.player.destroy();
      } catch (e) {
        // Ignore cleanup errors
      }
      this.player = null;
    }
    this.loading = false;
    this.errorMsg = null;
  }
}

// svelte-frontend/src/lib/components/ui/VideoPlayer.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import Hls from 'hls.js';
  import mpegts from 'mpegts.js';
  import { Play, Pause, Volume2, VolumeX, Maximize, AlertCircle, Loader2 } from 'lucide-svelte';

  let { 
    src = '', 
    title = 'Live Stream', 
    autoplay = true,
    muted = $bindable(false)
  } = $props();

  let videoElement: HTMLVideoElement;
  let hls: Hls | null = null;
  let mpegPlayer: any = null;
  
  let loading = $state(true);
  let error = $state<string | null>(null);
  let playing = $state(false);
  let volume = $state(1);
  let showControls = $state(true);
  let controlsTimeout: any;

  function initPlayer() {
    if (!videoElement || !src) return;
    
    // Reset state
    destroyPlayer();
    loading = true;
    error = null;

    const isHls = src.includes('.m3u8') || src.includes('format=hls');
    const isTs = src.includes('.ts') || src.includes('/stream/') || src.includes('format=ts');

    if (isHls) {
      if (Hls.isSupported()) {
        hls = new Hls({
          enableWorker: true,
          lowLatencyMode: true,
          backBufferLength: 60
        });
        hls.loadSource(src);
        hls.attachMedia(videoElement);
        hls.on(Hls.Events.MANIFEST_PARSED, () => {
          loading = false;
          if (autoplay) videoElement.play().catch(() => {
            // Autoplay blocked
            playing = false;
          });
        });
        hls.on(Hls.Events.ERROR, (_, data) => {
          if (data.fatal) {
            error = `HLS Error: ${data.details}`;
            loading = false;
          }
        });
      } else if (videoElement.canPlayType('application/vnd.apple.mpegurl')) {
        // Native HLS (Safari)
        videoElement.src = src;
        videoElement.addEventListener('loadedmetadata', () => {
          loading = false;
          if (autoplay) videoElement.play();
        });
      } else {
        error = "Your browser does not support HLS playback.";
        loading = false;
      }
    } else if (isTs) {
      if (mpegts.getFeatureList().mse) {
        mpegPlayer = mpegts.createPlayer({
          type: 'mse',
          isLive: true,
          url: src,
          cors: true
        });
        mpegPlayer.attachMediaElement(videoElement);
        mpegPlayer.load();
        
        mpegPlayer.on(mpegts.Events.ERROR, (type: any, detail: any) => {
          error = `Stream Error: ${type} (${detail})`;
          loading = false;
        });
        
        mpegPlayer.on(mpegts.Events.METADATA_ARRIVED, () => {
          loading = false;
          if (autoplay) videoElement.play().catch(() => {});
        });

        // Some streams don't trigger metadata arrived early enough
        setTimeout(() => {
          if (loading) loading = false;
        }, 3000);

      } else {
        error = "Your browser does not support MPEG-TS (MSE) playback.";
        loading = false;
      }
    } else {
      // Generic fallback
      videoElement.src = src;
      videoElement.addEventListener('canplay', () => {
        loading = false;
        if (autoplay) videoElement.play();
      });
      videoElement.addEventListener('error', () => {
        error = "Failed to load video stream.";
        loading = false;
      });
    }
  }

  function destroyPlayer() {
    if (hls) {
      hls.destroy();
      hls = null;
    }
    if (mpegPlayer) {
      mpegPlayer.unload();
      mpegPlayer.detachMediaElement();
      mpegPlayer.destroy();
      mpegPlayer = null;
    }
    if (videoElement) {
      videoElement.src = '';
      videoElement.load();
    }
  }

  function togglePlay() {
    if (videoElement.paused) videoElement.play();
    else videoElement.pause();
  }

  function toggleMute() {
    muted = !muted;
  }

  function toggleFullscreen() {
    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      videoElement.parentElement?.requestFullscreen();
    }
  }

  function handleMouseMove() {
    showControls = true;
    clearTimeout(controlsTimeout);
    controlsTimeout = setTimeout(() => {
      if (playing) showControls = false;
    }, 3000);
  }

  $effect(() => {
    if (src) initPlayer();
    return () => destroyPlayer();
  });

  onMount(() => {
    handleMouseMove();
  });

  onDestroy(() => {
    destroyPlayer();
    clearTimeout(controlsTimeout);
  });
</script>

<div class="video-wrapper" onmousemove={handleMouseMove} role="presentation">
  <!-- svelte-ignore a11y_media_has_caption -->
  <video
    bind:this={videoElement}
    bind:paused={playing}
    bind:muted={muted}
    bind:volume={volume}
    playsinline
    class="video-element"
    onclick={togglePlay}
  ></video>

  {#if loading}
    <div class="overlay loading-overlay">
      <Loader2 class="spinning" size={48} />
      <span>Connecting to stream...</span>
    </div>
  {/if}

  {#if error}
    <div class="overlay error-overlay">
      <AlertCircle size={48} color="var(--accent)" />
      <span class="error-text">{error}</span>
      <button class="btn btn-secondary" onclick={initPlayer}>Try Again</button>
    </div>
  {/if}

  <!-- Custom Controls Overlay -->
  <div class="controls-overlay" class:visible={showControls || !playing || error}>
    <div class="controls-top">
      <span class="stream-title">{title}</span>
    </div>

    <div class="controls-bottom">
      <div class="controls-left">
        <button class="control-btn" onclick={togglePlay}>
          {#if playing}
            <Pause size={20} fill="currentColor" />
          {:else}
            <Play size={20} fill="currentColor" />
          {/if}
        </button>

        <button class="control-btn" onclick={toggleMute}>
          {#if muted || volume === 0}
            <VolumeX size={20} />
          {:else}
            <Volume2 size={20} />
          {/if}
        </button>
        
        <input 
          type="range" 
          min="0" 
          max="1" 
          step="0.05" 
          bind:value={volume} 
          class="volume-slider" 
        />
      </div>

      <div class="controls-right">
        <div class="live-indicator">
          <span class="dot"></span>
          LIVE
        </div>
        <button class="control-btn" onclick={toggleFullscreen}>
          <Maximize size={20} />
        </button>
      </div>
    </div>
  </div>
</div>

<style lang="less">
  .video-wrapper {
    position: relative;
    width: 100%;
    aspect-ratio: 16 / 9;
    background: #000;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: inherit;

    &:fullscreen {
      aspect-ratio: auto;
      width: 100vw;
      height: 100vh;
      border-radius: 0;
    }
  }

  .video-element {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }

  .overlay {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 16px;
    background: rgba(0, 0, 0, 0.7);
    backdrop-filter: blur(8px);
    -webkit-backdrop-filter: blur(8px);
    z-index: 10;
    color: white;
    text-align: center;
    padding: 24px;
  }

  .error-text {
    color: #fca5a5;
    font-size: 14px;
    max-width: 300px;
  }

  .controls-overlay {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    padding: 20px;
    background: linear-gradient(to bottom, rgba(0,0,0,0.6) 0%, transparent 20%, transparent 80%, rgba(0,0,0,0.8) 100%);
    opacity: 0;
    transition: opacity 0.3s ease;
    z-index: 5;
    pointer-events: none;

    &.visible {
      opacity: 1;
      pointer-events: auto;
    }
  }

  .controls-top {
    .stream-title {
      font-size: 16px;
      font-weight: 700;
      color: white;
      text-shadow: 0 2px 4px rgba(0,0,0,0.5);
    }
  }

  .controls-bottom {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .controls-left, .controls-right {
    display: flex;
    align-items: center;
    gap: 16px;
  }

  .control-btn {
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 8px;
    border-radius: 50%;
    transition: background 0.2s;

    &:hover {
      background: rgba(255, 255, 255, 0.1);
    }
  }

  .volume-slider {
    width: 80px;
    height: 4px;
    accent-color: var(--accent);
    cursor: pointer;
  }

  .live-indicator {
    display: flex;
    align-items: center;
    gap: 6px;
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
    font-size: 11px;
    font-weight: 800;
    padding: 4px 10px;
    border-radius: 4px;
    border: 1px solid rgba(239, 68, 68, 0.3);

    .dot {
      width: 6px;
      height: 6px;
      background: #ef4444;
      border-radius: 50%;
      box-shadow: 0 0 4px #ef4444;
      animation: pulse 1.5s infinite;
    }
  }

  @keyframes pulse {
    0% { opacity: 1; }
    50% { opacity: 0.4; }
    100% { opacity: 1; }
  }

  .spinning {
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }
</style>
