// Dispatcharr-main/frontend/src/pages/StreamChecker.jsx
import React, { useState, useEffect } from 'react';
import {
  Box,
  Title,
  Tabs,
  Button,
  Group,
  Text,
  Progress,
  Paper,
  Card,
  Badge,
  Stack,
  Loader,
  Grid,
  RingProgress,
  Center,
  Slider,
  ActionIcon,
  Table
} from '@mantine/core';
import {
  Settings,
  Wand2,
  CheckSquare,
  Play,
  SquarePen,
  Trash2
} from 'lucide-react';
import ChannelsTable from '../components/tables/ChannelsTable';
import API from '../api';
import useChannelsTableStore from '../store/channelsTable';
import { notifications } from '@mantine/notifications';
import SortingRuleForm from '../components/forms/SortingRuleForm';

const StreamChecker = () => {
  const [activeTab, setActiveTab] = useState('bulk');
  const [status, setStatus] = useState({
    is_running: false,
    total: 0,
    completed: 0,
    successful: 0,
    failed: 0,
    current_stream_id: null,
    current_stream_name: null,
    workers: [],
    last_results: []
  });
  const [parallelProviders, setParallelProviders] = useState(1);

  const selectedChannelIds = useChannelsTableStore((state) => state.selectedChannelIds) || [];
  const setSelectedChannelIds = useChannelsTableStore((state) => state.setSelectedChannelIds);
  const channels = useChannelsTableStore((state) => state.channels);

  // Sorting Rules State
  const [rules, setRules] = useState([]);
  const [ruleModalOpen, setRuleModalOpen] = useState(false);
  const [editingRule, setEditingRule] = useState(null);

  const fetchRules = async () => {
    try {
      const data = await API.listSortingRules();
      if (data) setRules(data);
    } catch (e) {
      console.error('Failed to fetch sorting rules', e);
    }
  };

  const fetchSettings = async () => {
    try {
      const data = await API.listSettings();
      const streamSettings = data.find(s => s.key === 'stream_settings');
      if (streamSettings && streamSettings.value && streamSettings.value.stream_checker_parallel_providers) {
        setParallelProviders(streamSettings.value.stream_checker_parallel_providers);
      }
    } catch(e) {
      console.error('Failed to fetch settings', e);
    }
  };

  const updateParallelProviders = async (value) => {
    setParallelProviders(value);
    try {
      const data = await API.listSettings();
      let streamSettings = data.find(s => s.key === 'stream_settings');
      if (streamSettings) {
        const updatedValue = { ...streamSettings.value, stream_checker_parallel_providers: value };
        await API.updateSetting(streamSettings.id, {
          key: streamSettings.key,
          name: streamSettings.name,
          value: updatedValue
        });
        notifications.show({ title: 'Saved', message: 'Parallel providers setting saved', color: 'green' });
      } else {
        await API.createSetting({
          key: 'stream_settings',
          name: 'Stream Settings',
          value: { stream_checker_parallel_providers: value }
        });
      }
    } catch(e) {
      console.error('Failed to update setting', e);
      notifications.show({ title: 'Error', message: 'Failed to save setting', color: 'red' });
    }
  };

  useEffect(() => {
    fetchRules();
    fetchSettings();
  }, []);

  useEffect(() => {
    let interval;
    const fetchStatus = async () => {
      try {
        const res = await API.getBulkCheckStatus();
        if (res) setStatus(res);
      } catch (e) {
        console.error('Failed to get status', e);
      }
    };

    fetchStatus();
    interval = setInterval(fetchStatus, 1000);
    return () => clearInterval(interval);
  }, []);

  const handleStartBulkCheck = async () => {
    if (selectedChannelIds.length === 0) {
      notifications.show({ title: 'Error', message: 'No channels selected for checking.', color: 'red' });
      return;
    }

    const streamIdsToTest = [];
    selectedChannelIds.forEach((channelId) => {
      const channel = channels.find((c) => c.id === channelId);
      if (channel && channel.streams) {
        channel.streams.forEach((streamObj) => {
          if (streamObj.id) {
            streamIdsToTest.push(streamObj.id);
          } else if (streamObj.stream && streamObj.stream.id) {
            streamIdsToTest.push(streamObj.stream.id);
          }
        });
      }
    });

    if (streamIdsToTest.length === 0) {
      notifications.show({ title: 'Notice', message: 'The selected channels have no streams assigned to them.', color: 'yellow' });
      return;
    }

    try {
      await API.startBulkCheck(streamIdsToTest);
      notifications.show({ title: 'Started', message: `Started checking streams across ${selectedChannelIds.length} channels...`, color: 'blue' });
      setSelectedChannelIds([]);
    } catch (e) {
      notifications.show({ title: 'Error', message: 'Failed to start bulk check.', color: 'red' });
    }
  };

  const progressPercent = status.total > 0 ? (status.completed / status.total) * 100 : 0;

  return (
    <Box p="md">
      <Group justify="space-between" mb="md">
        <Title order={2}>Stream Checker Engine</Title>
      </Group>

      <Tabs value={activeTab} onChange={setActiveTab} variant="outline" radius="md">
        <Tabs.List>
          <Tabs.Tab value="bulk" leftSection={<CheckSquare size={16} />}>Bulk Tester</Tabs.Tab>
          <Tabs.Tab value="sorting" leftSection={<Settings size={16} />}>Sorting Rules</Tabs.Tab>
          <Tabs.Tab value="auto" leftSection={<Wand2 size={16} />}>Auto-Assignment</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="bulk" pt="xl">
          <Grid>
            <Grid.Col span={8}>
              <Paper withBorder shadow="sm" p="md" radius="md" mb="xl">
                <Group justify="space-between" mb="md">
                  <Box>
                    <Title order={4}>Select Channels to Test</Title>
                    <Text size="sm" c="dimmed">
                      Select channels. The Bulk Tester will test M3U streams within them in parallel by provider.
                    </Text>
                  </Box>
                  <Group>
                    <Button leftSection={<Wand2 size={16} />} color="violet" disabled={selectedChannelIds.length === 0 || status.is_running}
                      onClick={async () => {
                        try {
                          await API.bulkSortStreams(selectedChannelIds);
                          notifications.show({ title: 'Success', message: 'Successfully sorted streams!', color: 'green' });
                          setSelectedChannelIds([]);
                        } catch (e) {
                          notifications.show({ title: 'Error', message: 'Failed to sort streams.', color: 'red' });
                        }
                      }}>
                      Auto-Sort ({selectedChannelIds.length})
                    </Button>
                    <Button leftSection={<Play size={16} />} color="blue" disabled={selectedChannelIds.length === 0 || status.is_running} onClick={handleStartBulkCheck}>
                      Start Bulk Check ({selectedChannelIds.length})
                    </Button>
                  </Group>
                </Group>
              </Paper>
              <Box style={{ border: '1px solid #333', borderRadius: '8px', overflow: 'hidden' }}>
                 <ChannelsTable hideLinks={true} streamCheckerMode={true} />
              </Box>
            </Grid.Col>

            <Grid.Col span={4}>
              <Stack gap="md">
                <Card withBorder shadow="sm" radius="md" p="md">
                  <Title order={5} mb="sm">Settings</Title>
                  <Text size="sm" fw={500} mb={5}>Max Concurrent Providers</Text>
                  <Text size="xs" c="dimmed" mb="sm">Higher numbers check streams faster but consume more bandwidth.</Text>
                  <Slider 
                    value={parallelProviders} 
                    onChange={setParallelProviders}
                    onChangeEnd={updateParallelProviders}
                    min={1} 
                    max={10} 
                    marks={[{ value: 1, label: '1' }, { value: 5, label: '5' }, { value: 10, label: '10' }]} 
                    mb="lg"
                    disabled={status.is_running}
                  />
                </Card>

                <Card withBorder shadow="md" radius="lg" style={{ borderLeft: '4px solid var(--mantine-color-blue-filled)' }}>
                  <Stack gap="md">
                    <Stack gap={0}>
                      <Text fw={800} size="xl" variant="gradient" gradient={{ from: 'blue', to: 'cyan', deg: 45 }}>Analytics</Text>
                      <Text size="sm" c="dimmed">Overall Bulk Check Progress</Text>
                    </Stack>
                    
                    <Group justify="space-between">
                      <Badge color="blue" variant="light">Total: {status.total}</Badge>
                      <Badge color="green" variant="light">Success: {status.successful}</Badge>
                      <Badge color="red" variant="light">Failed: {status.failed}</Badge>
                    </Group>

                    <Box>
                      <Group justify="space-between" mb={5}>
                        <Text size="sm" fw={600}>{Math.round(progressPercent)}%</Text>
                        <Text size="sm" c="dimmed">{status.completed} / {status.total}</Text>
                      </Group>
                      <Progress value={progressPercent} size="xl" radius="xl" animated={status.is_running} color="blue" striped={status.is_running} />
                    </Box>

                    {status.workers && status.workers.length > 0 && (
                      <Box mt="sm">
                        <Text size="xs" c="dimmed" fw={700} tt="uppercase" mb="xs">Active Workers</Text>
                        <Stack gap="sm">
                          {status.workers.map((worker) => {
                            const workerProgress = worker.total > 0 ? (worker.completed / worker.total) * 100 : 0;
                            return (
                              <Paper key={worker.m3u_account_id} withBorder p="sm" radius="sm">
                                <Group wrap="nowrap" align="center">
                                  <RingProgress
                                    size={40}
                                    thickness={4}
                                    roundCaps
                                    sections={[{ value: workerProgress, color: 'blue' }]}
                                    label={<Center><Text size="10px" fw={700}>{Math.round(workerProgress)}%</Text></Center>}
                                  />
                                  <Stack gap={0} style={{ flex: 1 }}>
                                    <Text size="sm" fw={700} truncate>{worker.m3u_account_name}</Text>
                                    <Text size="xs" c="dimmed" truncate>{worker.current_stream_name || 'Idle'}</Text>
                                  </Stack>
                                </Group>
                              </Paper>
                            );
                          })}
                        </Stack>
                      </Box>
                    )}

                    <Box mt="sm">
                      <Text size="xs" c="dimmed" fw={700} tt="uppercase" mb="xs">Live Activity Log</Text>
                      <Paper withBorder p="xs" radius="md" bg="dark.7" style={{ maxHeight: '200px', overflowY: 'auto', fontFamily: 'monospace' }}>
                        {!status.last_results || status.last_results.length === 0 ? (
                          <Text size="xs" c="dimmed" fs="italic">Waiting for results...</Text>
                        ) : (
                          status.last_results.slice().reverse().map((s, i) => (
                            <Group key={`${s.id}-${i}`} justify="space-between" p={4} style={{ borderBottom: i < status.last_results.length - 1 ? '1px solid var(--mantine-color-dark-4)' : 'none' }}>
                              <Group gap="xs">
                                {s.stream_stats?.reachable ? <Text color="green" size="xs">✓</Text> : <Text color="red" size="xs">✗</Text>}
                                <Text size="xs" c="gray.3" truncate style={{ maxWidth: '150px' }}>{s.name}</Text>
                              </Group>
                              {s.stream_stats?.resolution && <Text size="xs" c="dimmed">{s.stream_stats.resolution}</Text>}
                            </Group>
                          ))
                        )}
                      </Paper>
                    </Box>
                  </Stack>
                </Card>
              </Stack>
            </Grid.Col>
          </Grid>
        </Tabs.Panel>

        <Tabs.Panel value="sorting" pt="xl">
          <Paper withBorder shadow="sm" p="md" radius="md" mb="md">
            <Group justify="space-between">
              <Box>
                <Title order={4}>Sorting Rules Engine</Title>
                <Text size="sm" c="dimmed">Create rules to automatically sort streams within your channels based on FFprobe metrics.</Text>
              </Box>
              <Button color="blue" onClick={() => { setEditingRule(null); setRuleModalOpen(true); }}>Add Rule</Button>
            </Group>
          </Paper>

          <Paper withBorder shadow="sm" p="md" radius="md">
             {rules.length === 0 ? (
               <Center p="xl"><Text c="dimmed" size="sm" fs="italic">No sorting rules defined yet. Create one above.</Text></Center>
             ) : (
               <Table striped highlightOnHover withTableBorder>
                 <Table.Thead>
                   <Table.Tr>
                     <Table.Th>Priority</Table.Th>
                     <Table.Th>Name</Table.Th>
                     <Table.Th>Condition</Table.Th>
                     <Table.Th>Score Modifier</Table.Th>
                     <Table.Th style={{ width: 100 }}>Actions</Table.Th>
                   </Table.Tr>
                 </Table.Thead>
                 <Table.Tbody>
                   {rules.sort((a,b) => a.priority - b.priority).map((rule) => (
                     <Table.Tr key={rule.id}>
                       <Table.Td>{rule.priority}</Table.Td>
                       <Table.Td fw={500}>{rule.name}</Table.Td>
                       <Table.Td>
                         <Badge variant="light" color="gray">
                           {rule.property.replace('stream_stats.', '')} {rule.operator} {rule.value}
                         </Badge>
                       </Table.Td>
                       <Table.Td>
                         <Badge color={rule.score_modifier > 0 ? 'green' : 'red'}>
                           {rule.score_modifier > 0 ? '+' : ''}{rule.score_modifier}
                         </Badge>
                       </Table.Td>
                       <Table.Td>
                         <Group gap="xs">
                           <ActionIcon variant="subtle" color="blue" onClick={() => { setEditingRule(rule); setRuleModalOpen(true); }}>
                             <SquarePen size={16} />
                           </ActionIcon>
                           <ActionIcon variant="subtle" color="red" onClick={async () => {
                             if (window.confirm('Delete this rule?')) {
                               await API.deleteSortingRule(rule.id);
                               fetchRules();
                             }
                           }}>
                             <Trash2 size={16} />
                           </ActionIcon>
                         </Group>
                       </Table.Td>
                     </Table.Tr>
                   ))}
                 </Table.Tbody>
               </Table>
             )}
          </Paper>
        </Tabs.Panel>

        <Tabs.Panel value="auto" pt="xl">
          <Paper withBorder shadow="sm" p="md" radius="md">
            <Title order={4}>Auto-Assignment Rules (Phase 3)</Title>
            <Text size="sm" c="dimmed" mt="xs">Create rules to automatically route newly imported M3U streams into existing channels. Coming soon!</Text>
          </Paper>
        </Tabs.Panel>
      </Tabs>

      <SortingRuleForm opened={ruleModalOpen} onClose={() => setRuleModalOpen(false)} rule={editingRule} onSuccess={fetchRules} />
    </Box>
  );
};

export default StreamChecker;

// svelte-frontend/src/routes/stream-checker/+page.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { Activity, Play, Square, Settings, CheckCircle2, XCircle, Clock, AlertCircle, RefreshCw } from 'lucide-svelte';
	import { api } from '$lib/api';
	import { toast } from '$lib/toast.svelte';

	// State
	let providers: any[] = $state([]);
	let selectedProviderId: number | '' = $state('');
	
	let streams: any[] = $state([]);
	let loadingStreams = $state(false);
	
	let selectedStreamIds: Set<number> = $state(new Set());
	let selectAll = $state(false);

	// Status State
	let status: any = $state(null);
	let pollingInterval: any = null;

	// Settings State
	let streamSettingsId: number | null = $state(null);
	let parallelProviders = $state(1);
	let loadingSettings = $state(false);

	onMount(async () => {
		loadSettings();
		providers = await api.getPlaylists().catch(() => []);
		checkStatus();
	});

	onDestroy(() => {
		if (pollingInterval) clearInterval(pollingInterval);
	});

	async function loadSettings() {
		try {
			loadingSettings = true;
			const settings = await api.getSettings();
			const streamSettings = settings.find((s: any) => s.key === 'stream_settings');
			if (streamSettings) {
				streamSettingsId = streamSettings.id;
				parallelProviders = streamSettings.value.stream_checker_parallel_providers || 1;
			}
		} catch (err) {
			console.error('Failed to load settings', err);
		} finally {
			loadingSettings = false;
		}
	}

	async function updateParallelProviders() {
		if (!streamSettingsId) return;
		try {
			// Fetch fresh settings first to merge
			const settingsList = await api.getSettings();
			const current = settingsList.find((s: any) => s.id === streamSettingsId);
			if (current) {
				const newValue = {
					...current.value,
					stream_checker_parallel_providers: parallelProviders
				};
				await api.updateSetting(streamSettingsId, { key: 'stream_settings', value: newValue });
			}
		} catch (err) {
			console.error('Failed to update concurrency', err);
		}
	}

	async function checkStatus() {
		try {
			const res = await api.getBulkCheckStatus();
			status = res;

			if (status.is_running && !pollingInterval) {
				pollingInterval = setInterval(checkStatus, 2000);
			} else if (!status.is_running && pollingInterval) {
				clearInterval(pollingInterval);
				pollingInterval = null;
			}
		} catch (err) {
			console.error(err);
		}
	}

	async function loadStreams() {
		if (!selectedProviderId) {
			streams = [];
			selectedStreamIds.clear();
			selectAll = false;
			return;
		}

		loadingStreams = true;
		try {
			streams = await api.getStreams({ m3u_account_id: selectedProviderId });
			selectedStreamIds.clear();
			selectAll = false;
		} catch (err) {
			console.error(err);
		} finally {
			loadingStreams = false;
		}
	}

	function toggleSelectAll() {
		selectAll = !selectAll;
		if (selectAll) {
			selectedStreamIds = new Set(streams.map(s => s.id));
		} else {
			selectedStreamIds.clear();
		}
	}

	function toggleStream(id: number) {
		const newSet = new Set(selectedStreamIds);
		if (newSet.has(id)) {
			newSet.delete(id);
			selectAll = false;
		} else {
			newSet.add(id);
			if (newSet.size === streams.length) selectAll = true;
		}
		selectedStreamIds = newSet;
	}

	async function startBulkCheck() {
		if (selectedStreamIds.size === 0) return;
		try {
			await api.bulkCheckStreams(Array.from(selectedStreamIds));
			// Give it a moment to initialize before polling
			setTimeout(checkStatus, 500);
		} catch (err: any) {
			toast.error(err.message || 'Failed to start bulk check');
		}
	}

	async function cancelBulkCheck() {
		try {
			await api.cancelBulkCheck();
		} catch (err: any) {
			toast.error(err.message || 'Failed to cancel');
		}
	}

	function getProgressPercentage() {
		if (!status || status.total === 0) return 0;
		return Math.round((status.completed / status.total) * 100);
	}
</script>

<div class="page-container">
	<header class="page-header">
		<div>
			<h1>Stream Checker</h1>
			<p class="subtitle">Bulk health testing for M3U streams</p>
		</div>
		
		<div class="header-settings">
			<div class="setting-item" title="Parallel Providers">
				<Settings size={16} class="icon-dim" />
				<label for="parallel">Concurrency:</label>
				<input 
					type="number" 
					id="parallel" 
					bind:value={parallelProviders} 
					min="1" 
					max="10"
					onchange={updateParallelProviders}
					disabled={loadingSettings || status?.is_running}
				/>
			</div>
		</div>
	</header>

	<div class="main-content">
		<!-- Left Panel: Selection -->
		<div class="selection-panel pane">
			<div class="pane-header">
				<h3>Select Streams</h3>
				<select bind:value={selectedProviderId} onchange={loadStreams} disabled={status?.is_running}>
					<option value="">-- Choose Provider --</option>
					{#each providers as provider}
						<option value={provider.id}>{provider.name}</option>
					{/each}
				</select>
			</div>

			<div class="pane-content">
				{#if loadingStreams}
					<div class="empty-state">
						<RefreshCw class="spin" size={24} />
						<p>Loading streams...</p>
					</div>
				{:else if !selectedProviderId}
					<div class="empty-state">
						<Activity size={32} class="icon-dim" />
						<p>Select a provider to load streams.</p>
					</div>
				{:else if streams.length === 0}
					<div class="empty-state">
						<AlertCircle size={32} class="icon-dim" />
						<p>No streams found for this provider.</p>
					</div>
				{:else}
					<div class="table-container">
						<table class="data-table">
							<thead>
								<tr>
									<th class="col-checkbox">
										<input type="checkbox" checked={selectAll} onchange={toggleSelectAll} disabled={status?.is_running} />
									</th>
									<th>Name</th>
									<th>Group</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								{#each streams as stream}
									<tr class:selected={selectedStreamIds.has(stream.id)} onclick={() => !status?.is_running && toggleStream(stream.id)}>
										<td class="col-checkbox" onclick={(e) => e.stopPropagation()}>
											<input type="checkbox" checked={selectedStreamIds.has(stream.id)} onchange={() => toggleStream(stream.id)} disabled={status?.is_running} />
										</td>
										<td class="col-name">{stream.name}</td>
										<td class="col-group">{stream.group_title || 'Uncategorized'}</td>
										<td class="col-status">
											{#if stream.stream_stats?.status === 'online'}
												<span class="badge success">Online</span>
											{:else if stream.stream_stats?.status}
												<span class="badge error">{stream.stream_stats.status}</span>
											{:else}
												<span class="badge dim">Untested</span>
											{/if}
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				{/if}
			</div>

			<div class="pane-footer">
				<div class="selection-info">
					{selectedStreamIds.size} streams selected
				</div>
				<button 
					class="btn-primary" 
					disabled={selectedStreamIds.size === 0 || status?.is_running}
					onclick={startBulkCheck}
				>
					<Play size={16} />
					<span>Start Test</span>
				</button>
			</div>
		</div>

		<!-- Right Panel: Status Dashboard -->
		<div class="status-panel pane">
			<div class="pane-header">
				<h3>Live Status</h3>
				{#if status?.is_running}
					<button class="btn-cancel" onclick={cancelBulkCheck}>
						<Square size={14} fill="currentColor" />
						<span>Cancel</span>
					</button>
				{/if}
			</div>

			<div class="pane-content status-content">
				{#if !status || (!status.is_running && status.total === 0)}
					<div class="empty-state">
						<Activity size={48} class="icon-dim" style="opacity: 0.5;" />
						<p>No active tests.</p>
					</div>
				{:else}
					<div class="progress-section">
						<div class="progress-stats">
							<div class="stat">
								<span class="val">{status.completed} / {status.total}</span>
								<span class="lbl">Completed</span>
							</div>
							<div class="stat success">
								<span class="val">{status.successful}</span>
								<span class="lbl">Online</span>
							</div>
							<div class="stat error">
								<span class="val">{status.failed}</span>
								<span class="lbl">Failed</span>
							</div>
						</div>
						
						<div class="progress-bar-container">
							<div class="progress-bar" style="width: {getProgressPercentage()}%"></div>
						</div>
					</div>

					{#if status.workers?.length > 0}
						<div class="workers-section">
							<h4>Active Workers</h4>
							<div class="workers-grid">
								{#each status.workers as worker}
									<div class="worker-card">
										<div class="worker-header">
											<span class="provider-name">{worker.m3u_account_name}</span>
											<span class="worker-progress">{worker.completed}/{worker.total}</span>
										</div>
										<div class="worker-current">
											<span class="truncate">Testing: {worker.current_stream_name || '...'}</span>
										</div>
									</div>
								{/each}
							</div>
						</div>
					{/if}

					<div class="results-section">
						<h4>Recent Results</h4>
						<div class="results-list">
							{#each status.last_results.slice().reverse() as res}
								<div class="result-card">
									<div class="res-icon">
										{#if res.reachable && res.status === 'online'}
											<CheckCircle2 size={18} class="text-success" />
										{:else}
											<XCircle size={18} class="text-error" />
										{/if}
									</div>
									<div class="res-info">
										<div class="res-name truncate">{res.name || 'Unknown Stream'}</div>
										<div class="res-meta">
											{#if res.reachable}
												<span>{res.resolution || 'Unknown res'}</span>
												<span>•</span>
												<span>{res.video_codec || 'N/A'}</span>
												<span>•</span>
												<span class={res.status === 'online' ? 'text-success' : 'text-error'}>{res.status}</span>
											{:else}
												<span class="text-error">Unreachable / Timeout</span>
											{/if}
										</div>
									</div>
								</div>
							{/each}
							{#if status.last_results.length === 0}
								<div class="empty-results">Waiting for results...</div>
							{/if}
						</div>
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>

<style lang="less">
	.page-container {
		display: flex;
		flex-direction: column;
		gap: 20px;
		height: 100%;
		overflow: hidden;
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: flex-end;
		flex-shrink: 0;

		h1 {
			font-size: 24px;
			font-weight: 700;
			color: var(--text-bright);
			margin: 0 0 4px 0;
		}

		.subtitle {
			color: var(--text-dim);
			margin: 0;
			font-size: 14px;
		}
	}

	.header-settings {
		.setting-item {
			display: flex;
			align-items: center;
			gap: 8px;
			background: var(--surface);
			border: 1px solid var(--border);
			padding: 6px 12px;
			border-radius: var(--radius);
			font-size: 13px;
			
			label {
				color: var(--text-dim);
				font-weight: 500;
			}

			input {
				background: rgba(0,0,0,0.2);
				border: 1px solid var(--border);
				color: var(--text-bright);
				width: 50px;
				padding: 4px;
				border-radius: 4px;
				text-align: center;
				
				&:focus {
					outline: none;
					border-color: var(--accent);
				}
				
				&:disabled {
					opacity: 0.5;
				}
			}
		}
	}

	.main-content {
		display: flex;
		gap: 20px;
		flex: 1;
		min-height: 0;
	}

	.pane {
		background: var(--surface);
		border: 1px solid var(--border);
		border-radius: var(--radius);
		display: flex;
		flex-direction: column;
		overflow: hidden;
	}

	.selection-panel {
		flex: 1;
		max-width: 60%;
	}

	.status-panel {
		flex: 1;
		background: rgba(0,0,0,0.2);
	}

	.pane-header {
		padding: 16px;
		border-bottom: 1px solid var(--border);
		background: var(--surface-bright);
		display: flex;
		justify-content: space-between;
		align-items: center;

		h3 {
			margin: 0;
			font-size: 16px;
			font-weight: 600;
			color: var(--text-bright);
		}

		select {
			background: rgba(0,0,0,0.2);
			border: 1px solid var(--border);
			color: var(--text-bright);
			padding: 6px 12px;
			border-radius: 4px;
			font-size: 13px;
			outline: none;

			&:focus { border-color: var(--accent); }
		}
	}

	.pane-content {
		flex: 1;
		overflow-y: auto;
		display: flex;
		flex-direction: column;
	}

	.empty-state {
		flex: 1;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		color: var(--text-dim);
		gap: 12px;
		padding: 32px;
		text-align: center;
		
		p { margin: 0; font-size: 14px; }
	}

	.table-container {
		flex: 1;
	}

	.data-table {
		width: 100%;
		border-collapse: collapse;
		font-size: 13px;

		th {
			position: sticky;
			top: 0;
			background: var(--surface-bright);
			text-align: left;
			padding: 10px 16px;
			font-weight: 600;
			color: var(--text-dim);
			border-bottom: 1px solid var(--border);
			z-index: 10;
		}

		td {
			padding: 10px 16px;
			border-bottom: 1px solid var(--border);
			color: var(--text-bright);
		}

		tr {
			transition: background 0.1s;
			cursor: pointer;

			&:hover {
				background: rgba(255, 255, 255, 0.02);
			}

			&.selected {
				background: rgba(255, 255, 255, 0.05);
			}
		}

		.col-checkbox {
			width: 40px;
			text-align: center;
			padding: 10px 8px;
		}

		.col-group {
			color: var(--text-dim);
			white-space: nowrap;
		}

		.col-name {
			max-width: 200px;
			white-space: nowrap;
			overflow: hidden;
			text-overflow: ellipsis;
		}
	}

	.badge {
		font-size: 11px;
		padding: 2px 6px;
		border-radius: 4px;
		font-weight: 600;
		text-transform: capitalize;

		&.success { background: rgba(74, 222, 128, 0.1); color: #4ade80; }
		&.error { background: rgba(237, 28, 36, 0.1); color: var(--accent); }
		&.dim { background: rgba(255, 255, 255, 0.1); color: var(--text-dim); }
	}

	.text-success { color: #4ade80; }
	.text-error { color: var(--accent); }

	.pane-footer {
		padding: 16px;
		border-top: 1px solid var(--border);
		background: var(--surface-bright);
		display: flex;
		justify-content: space-between;
		align-items: center;

		.selection-info {
			font-size: 13px;
			color: var(--text-dim);
			font-weight: 500;
		}
	}

	.btn-primary {
		display: flex;
		align-items: center;
		gap: 8px;
		background: var(--accent);
		color: white;
		border: none;
		padding: 8px 16px;
		border-radius: var(--radius);
		font-weight: 600;
		font-size: 13px;
		cursor: pointer;
		transition: all 0.2s;

		&:hover:not(:disabled) {
			background: var(--accent-dim);
		}

		&:disabled {
			opacity: 0.5;
			cursor: not-allowed;
		}
	}

	.btn-cancel {
		display: flex;
		align-items: center;
		gap: 6px;
		background: rgba(237, 28, 36, 0.1);
		border: 1px solid var(--accent);
		color: var(--accent);
		padding: 6px 12px;
		border-radius: var(--radius);
		font-size: 12px;
		font-weight: 600;
		cursor: pointer;

		&:hover {
			background: var(--accent);
			color: white;
		}
	}

	.status-content {
		padding: 24px;
		gap: 24px;
	}

	.progress-section {
		display: flex;
		flex-direction: column;
		gap: 12px;
		background: var(--surface);
		padding: 16px;
		border-radius: var(--radius);
		border: 1px solid var(--border);

		.progress-stats {
			display: flex;
			justify-content: space-between;
			
			.stat {
				display: flex;
				flex-direction: column;
				align-items: center;
				
				.val { font-size: 20px; font-weight: 700; color: var(--text-bright); }
				.lbl { font-size: 11px; text-transform: uppercase; color: var(--text-dim); letter-spacing: 0.5px; }
				
				&.success .val { color: #4ade80; }
				&.error .val { color: var(--accent); }
			}
		}

		.progress-bar-container {
			height: 8px;
			background: rgba(255, 255, 255, 0.1);
			border-radius: 4px;
			overflow: hidden;

			.progress-bar {
				height: 100%;
				background: var(--accent);
				transition: width 0.3s ease;
			}
		}
	}

	.workers-section {
		h4 {
			font-size: 13px;
			text-transform: uppercase;
			color: var(--text-dim);
			margin: 0 0 12px 0;
			letter-spacing: 0.5px;
		}

		.workers-grid {
			display: grid;
			grid-template-columns: 1fr;
			gap: 8px;
		}

		.worker-card {
			background: var(--surface);
			border: 1px solid var(--border);
			padding: 12px;
			border-radius: var(--radius);
			display: flex;
			flex-direction: column;
			gap: 4px;

			.worker-header {
				display: flex;
				justify-content: space-between;
				font-size: 12px;
				font-weight: 600;
				color: var(--text-bright);
			}

			.worker-current {
				font-size: 11px;
				color: var(--text-dim);
				
				.truncate {
					display: block;
					white-space: nowrap;
					overflow: hidden;
					text-overflow: ellipsis;
				}
			}
		}
	}

	.results-section {
		flex: 1;
		display: flex;
		flex-direction: column;
		min-height: 0;

		h4 {
			font-size: 13px;
			text-transform: uppercase;
			color: var(--text-dim);
			margin: 0 0 12px 0;
			letter-spacing: 0.5px;
		}

		.results-list {
			display: flex;
			flex-direction: column;
			gap: 8px;
			overflow-y: auto;
			padding-right: 4px;

			.empty-results {
				text-align: center;
				padding: 20px;
				color: var(--text-dim);
				font-size: 13px;
				font-style: italic;
			}
		}

		.result-card {
			display: flex;
			gap: 12px;
			background: var(--surface);
			border: 1px solid var(--border);
			padding: 12px;
			border-radius: var(--radius);
			align-items: center;

			.res-icon {
				display: flex;
				align-items: center;
				justify-content: center;
			}

			.res-info {
				flex: 1;
				min-width: 0;

				.res-name {
					font-size: 13px;
					font-weight: 600;
					color: var(--text-bright);
					margin-bottom: 2px;
				}

				.res-meta {
					display: flex;
					gap: 6px;
					font-size: 11px;
					color: var(--text-dim);
					align-items: center;
				}

				.truncate {
					white-space: nowrap;
					overflow: hidden;
					text-overflow: ellipsis;
				}
			}
		}
	}

	.spin {
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		100% { transform: rotate(360deg); }
	}
</style>
